export const myPermissionsArray = [
    "statusListCreate",
    "statusListRead",
    "statusListUpdate",
    "statusListDelete",

    "ticketCreate", // دسترسی ایجاد تیکت
    "ticketCreateAdvanced", // دسترسی ایجاد تیکت پیشرفته
    "readAllTicketsInSystem", // خواندن کل تیکت های سیتم
    "ticketChatList", // مشاهده ی چت لیست بعد از کلیک روی گزینه ی مشاهده
    "ticketReadOwn",
    "readMyAllTickets",
    "ticketReadOwnReceived",
    "ticketUpdate",
    "ticketDelete",
    "themeCreate",
    "themeRead",
    "themeUpdate",
    "themeDelete",
    "departmentCreate",
    "departmentRead",
    "departmentUpdate",
    "departmentDelete",
    "fileCreate",
    "fileRead",
    "fileUpdate",
    "fileDelete",
    "tasksCreateFullAccessToUsers",
    "tasksCreateToAssignSameDepartment",
    "tasksReadAll",
    "tasksOwnRead",
    "tasksUpdateAll",
    "tasksOwnUpdate",
    "tasksDeleteAll",
    "tasksOwnDelete",
    "rolesCreate",
    "rolesRead",
    "rolesUpdate",
    "rolesDelete",
    "ticketRepliesCreate",
    "ticketRepliesRead",
    "ticketRepliesUpdate",
    "ticketRepliesDelete",
    "ticketChangeHistoryRead",
    "ticketChangeHistoryRepliesUpdate",
    "ticketChangeHistoryDelete",
    "userCreate",
    "userReadAll",
    "userReadSameDepartment",
    "userUpdateAll",
    "userUpdateSameDepartment",
    "userDeleteAll",
    "userDeleteSameDepartment",
    "userActiveAndDeActiveUsers",
    "userEditUsersRole",
    "userEditUsersDepartment",
    "report",
    "howManyUsersThereAre",
    "howManyUsersIsInEveryDepartment",
    "howManyTicketsThereAre",
    "howManyTicketsThereAreInEveryDepartment",
    "howManyTicketsHasDoneStatus",
    "howManyTicketsHasDoneStatusIn12Month",
    "UnlimitedForward",
    "forwardTickets", // قابلیت ارجاع تیکت ها
    "assignTicketsInbox", // مشاهده صندوق ورودی از توی جدول ارجاعات
    "assignTicketsInboxCanDelete", // قابلیت حذف از توی جدول ارجاع های من توی صندوق ورودی
    "assignTicketsOutBox", //  مشاهده ی صندوق خروجی - ارسالی هایی که من به دیگران ارجاع دادم
    "assignTicketsOutBoxCanDelete", // قابلیت حذف از توی جدول ارجاع های من توی صندوق خروجی
    "assignTicketsShowAll", // مشاهده ی کل جدول ارجاعات برای مدیر که بتونه کل تیکت های ارجاعی رو ببینه
    "adminSettings",
    "userStatusInDashboard",
    "sendHiddenMessage",
    "smsSend",
    // حسابفا
    "showBillAccess",
    "downloadBillAsPdf",
    "downloadBillAsCsv",
    "submitBillInSubmitOrderForm",
    "submitBillInChatList",
    "saveBillAsDraft",
    "saveBillAsDone",
    "deleteBill",
    "allContactsWhenSubmitBill",
    "editBillInChatList",
    ///////////
    "showReportBillList", // درسترسی به لیست فاکتور فروش و فیلتر پیوت
    "adminReport",
    "basteBandi",
    "ersal",
    "hasAccessToUnCheckedSendPackages", // بسته هایی که ارسال شده رو بتونه از حالت ارسال شده تغییر بده به حالت ارسال نشده؟
    ////////////////////////
    "widgetUserStatus",
    "widgetNumberOfBills7days",
    "widgetAmountOfBills7days",
    "widgetHowManyUsersThereAre",
    //////////////////////
    "screenShotBills",
    "fatherAccess",
    "showMyBillListForCustomer",
    "viewBills",
    "testBillCalculatePrice",
    "myBankFirstUserId",
    "allBanksFirstUserId",
    "myBankDepartment",
    "showMyTicketList",
    //////////////////////////// Dashboard Access
    "customerDashboard",
    "organizationDashboard",
    "departmentAdminDashboard",
    "fullAdminDashboard",

]