export const departmentObject = {
    name: "adminDepartment",
    description: "adminDepartment",
    // userId,
    // managerUserId,
    // parentDepartmentId,
    // location,
    // address,
    // phoneNumber,
    // emailAddress,
    // contactInfo,
    // sendSmsAfterSubmitResponse,
    // smsText,
    // departmentAccessToSendTicket,
    // departmentAccessToReplyTicket,
    // departmentAccessToArchiveTicket,
    // departmentAccessToTaskSection,
    // departmentTaskColor,
    // departmentAccessToArchiveTasks,
    // accessToSameDepartmentToAssignTask,
    // accessToOtherUsersToAssignTask
}