export const roleObject = {
        name:"adminRole",
        statusListCreate:true,
        statusListRead:true,
        statusListUpdate:true,
        statusListDelete:true,
        ticketCreate:true, // ایجاد تیکت جدید
        readAllTicketsInSystem:true, // خواند همه ی تیکت ها برای ادمین
        ticketChatList:true, // مشاهده چت لیست
        ticketReadOwn:true, // خواندن تیکت هایی که خودم باز کردم و ایجاد کردم برای مشتریان
        ticketReadOwnReceived:true, // تمام تیکت هایی که من توی مدل کاربر  در بخش تیکت بهشون دسترسی دارم
        ticketUpdate:true,
        ticketDelete:true,
        themeCreate:true,
        themeRead:true,
        themeUpdate:true,
        themeDelete:true,
        departmentCreate:true,
        departmentRead:true,
        departmentUpdate:true,
        departmentDelete:true,
        fileCreate:true,
        fileRead:true,
        fileUpdate:true,
        fileDelete :true,
        tasksCreateFullAccessToUsers:true,
        tasksCreateToAssignSameDepartment :true,
        tasksReadAll:true,
        tasksOwnRead:true,
        tasksUpdateAll:true,
        tasksOwnUpdate:true,
        tasksDeleteAll:true,
        tasksOwnDelete:true,
        rolesCreate:true,
        rolesRead:true,
        rolesUpdate:true,
        rolesDelete:true,
        ticketRepliesCreate:true,
        ticketRepliesRead:true,
        ticketRepliesUpdate:true,
        ticketRepliesDelete:true,
        ticketChangeHistoryRead:true,
        ticketChangeHistoryRepliesUpdate:true,
        ticketChangeHistoryDelete:true,
        forwardTickets:true,
        UnlimitedForward:true,
        userCreate:true,
        userReadAll:true,
        userActiveAndDeActiveUsers:true,
        userEditUsersRole:true,
        userEditUsersDepartment:true,
        adminSettings:true,
        userStatusInDashboard:true,
        userReadSameDepartment:true,
        userUpdateAll:true,
        userUpdateSameDepartment:true,
        userDeleteAll:true,
        userDeleteSameDepartment:true,
        report:true,
        howManyUsersThereAre:true,
        howManyUsersIsInEveryDepartment:true,
        howManyTicketsThereAre:true,
        howManyTicketsThereAreInEveryDepartment:true,
        howManyTicketsHasDoneStatus:true,
        howManyTicketsHasDoneStatusIn12Month:true,
        sendHiddenMessage:true,
        // smsArchive:true,
        // smsPending:true,
        smsSend:true,

        showBillAccess:true,
        downloadBillAsPdf:true,
        downloadBillAsCsv:true,
        submitBillInSubmitOrderForm:true,
        submitBillInChatList:true,
        saveBillAsDraft:true,
        saveBillAsDone:true,
        deleteBill:true,
        editBillInChatList:true,
        allContactsWhenSubmitBill:true,
        showReportBillList:true,
        adminReport:true,
        basteBandi:true,
        ersal:true,
        hasAccessToUnCheckedSendPackages:true,
        // widget
        widgetUserStatus:true,
        widgetNumberOfBills7days:true,
        widgetAmountOfBills7days:true,
        widgetHowManyUsersThereAre:true,
        // ادامه دارد....
        screenShotBills:true,

}